name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install
        working-directory: ./Day-5/meetups

      - name: Build Web release
        run: |
          npx expo build:web
        working-directory: ./Day-5/meetups

      - name: Test
        run: npm test
        working-directory: ./Day-5/meetups
